- name: Configure EC2 for aCloudBridge Application
  hosts: ec2
  become: yes

  tasks:
    - name: Gathering Facts
      setup:

    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Node.js (using nvm) and npm
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
        . ~/.bashrc
        nvm install 22
        nvm use 22
        npm install -g npm@latest
        echo "NVM installed and npm updated"
        echo "NVM version: $(nvm --version)"
        echo "NVM path: $(which nvm)"
        echo "NPM version: $(npm --version)"
        echo "NPM path: $(which npm)"
        echo "PATH: $PATH"
      become_user: ec2-user

    - name: Clone aCloudBridge Repository
      git:
        repo: "https://{{ githubuser }}:{{ githubpassword }}@github.com/prabeeshbalan/aCloudBridge.git"
        dest: ~/aCloudBridge
      become_user: ec2-user

    - name: Debug List frontend directory
      shell: ls -l ~/aCloudBridge/frontend
      become_user: ec2-user

    - name: Install Frontend Dependencies
      shell: |
        source /home/ec2-user/.bashrc
        nvm exec npm install
      args:
        chdir: ~/aCloudBridge/frontend
      become_user: ec2-user

    - name: Install Backend Dependencies
      shell: |
        source /home/ec2-user/.bashrc
        nvm exec npm install
      args:
        chdir: ~/aCloudBridge/backend
      become_user: ec2-user

    - name: Install PM2 Globally
      shell: |
        source /home/ec2-user/.bashrc
        nvm exec npm install -g pm2
      become_user: ec2-user

    - name: Build Frontend
      shell: |
        source /home/ec2-user/.bashrc
        nvm exec npm run build
      args:
        chdir: ~/aCloudBridge/frontend
      become_user: ec2-user

    - name: Build Backend
      shell: |
        source /home/ec2-user/.bashrc
        nvm exec npm run build
      args:
        chdir: ~/aCloudBridge/backend
      become_user: ec2-user

    - name: Deploy Backend Configuration
      template:
        src: server.js.j2
        dest: ~/aCloudBridge/backend/server.js
      become_user: ec2-user
      environment:
        DB_HOST: "{{ lookup('terraform_output', 'db_endpoint') }}"
        DB_USER: "{{ lookup('terraform_output', 'db_username') }}"
        DB_PASSWORD: "{{ lookup('terraform_output', 'db_password') }}"
        DB_NAME: "{{ lookup('terraform_output', 'db_name') }}"

    - name: Start Frontend with PM2
      shell: |
        source /home/ec2-user/.bashrc
        nvm exec pm2 start npm --name acloudbridge-frontend -- start
      args:
        chdir: ~/aCloudBridge/frontend
      become_user: ec2-user

    - name: Start Backend with PM2
      shell: |
        source /home/ec2-user/.bashrc
        nvm exec pm2 start server.js --name acloudbridge-backend
      args:
        chdir: ~/aCloudBridge/backend
      become_user: ec2-user